name: RoodCore
version: 1.0
description: R00DCore
author: cooltimmetje
depend: [TitleManager]
main: me.cooltimmetje.RoodCore.Main
commands:
    time:
        description: time
    cooldown:
        description: cooldown
    tokens:
        description: tokens
    tokenshop:
        description: tokenshop
    codetim:
        description: codetim
    coderood:
        description: coderood